package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/riyadennis/ingestion-service/business"
	"github.com/riyadennis/ingestion-service/graph/generated"
	"github.com/riyadennis/ingestion-service/graph/model"
)

// SingleUpload is the resolver for the singleUpload field.
func (r *mutationResolver) SingleUpload(ctx context.Context, file graphql.Upload) (bool, error) {
	r.Logger.Infof("uploading file content type: %s", file.ContentType)
	userID := ctx.Value(UserIDContextKey).(*string)
	if *userID == "" {
		r.Logger.Error("unauthorised request, userID not present in context")
		return false, errors.New("userID not present in context")
	}

	fu := &business.FileUpload{
		RealName:    file.Filename,
		FileName:    business.SanitizeFilename(file.Filename),
		Size:        file.Size,
		ContentType: file.ContentType,
		File:        file.File,
		UserID:      *userID,
	}
	err := fu.Upload(ctx, r.Resolver.Uploader.Storage, r.Resolver.Uploader.BucketName)
	if err != nil {
		return false, err
	}

	return true, nil
}

// FetchFile is the resolver for the FetchFile field.
func (r *queryResolver) FetchFile(ctx context.Context, name *string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: FetchFile - FetchFile"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
