// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type File struct {
	Size     *string `json:"Size,omitempty"`
	CreateAt *string `json:"CreateAt,omitempty"`
	UserID   *string `json:"UserID,omitempty"`
	Content  *string `json:"Content,omitempty"`
}

// The `Mutation` type, represents all updates we can make to our data.
type Mutation struct {
}

// The `Query` type, represents all of the entry points into our object graph.
type Query struct {
}
